### ISSUE TITLE
[GUI] Add uniform random via key modifier on Randomize  function

### ISSUE THREAD

**Issue by ricardomatias** [openrndr/orx#28]
At the moment the randomize gives back values close to each other. Would be nice to have an uniform randomizer via Control/Command click.

**Comment by hamoid** [comment]
It has a default randomization strength of 0.05:

https://github.com/openrndr/orx/blob/master/orx-gui/src/main/kotlin/Gui.kt#L490

Maybe GUI could have a setRandomizationStrength() method to change it?

**Comment by edwinRNDR** [comment]
I added strength because full randomization made too big of a jump between settings for me. Indeed settings the strength to 1.0 would give the behavior @ricardomatias wants, and this can indeed be exposed. I am also ok with key modifiers as proposed here.

There are some other problems with randomization that I noticed:
 - Randomization of integer values is biased because of the truncation instead of round.
 - I disabled randomization of boolean values because boolean values are often values that should not be randomized.
 - Should we have randomization per compartment?

**Comment by ricardomatias** [comment]
I'd go with @hamoid suggestion and allow it to be customizable. While also adding a modifier for an easy 1.0 strength go to. 

- Thankfully Kotlin provides `roundToInt` :)
- Agreed

If we go for randomization per compartment then I'd suggest using an [icon](https://www.flaticon.com/free-icon/shuffle_724979?term=random&page=1&position=1) for space reasons. Perhaps we can keep the global and add per compartment.

**Comment by hamoid** [comment]
I wanted to leave here a thought in a different direction.  During the last year I have been trying to not have the "slot-machine" effect in the creative tools I write. I used to create lots of programs that would randomize things, then I just keep pressing a key to get new designs until I find something I like and then save it. I decided instead to have more control and intention in the generative designs I produce, in a way that it would let me explore randomness. For example by having knobs that scan the noise space, so subtle tweaks produce subtle changes.

I say this when seeing that the randomization aspect becomes a very visible feature of the GUI, specially if there's one per section. 

Maybe it would be nice that randomization can be switched off? :)

**Comment by edwinRNDR** [comment]
@hamoid that's a fair point too :)

**Comment by hamoid** [comment]
What do you think of being able to specify randomization amount per input? Maybe someone wants to randomize booleans. Maybe there are only booleans in that gui :) Someone may want one control fully randomized, while another just changes 1%. Would that make sense?

Also, I've written looots of programs that are controlled with the keyboard. Which can be bad, because it's opaque. Could we add tooltips to guis, so when we take a project two weeks later the tooltip reminds us of keys we can use or what a certain input does? For example if Shift does a big randomization, it could say so in the tooltip.

**Comment by ricardomatias** [comment]
Closing since this has been added
